const $=id=>document.getElementById(id);
const clues=[
{id:'phish',label:'The message',title:'A fake staff email',detail:'At 08:41, someone sent a message that looked like an internal file-sharing notice. The sender address used “aur0ra” with a zero instead of an “o”. It asked an employee to open an attachment.',lesson:'A familiar display name is not proof. Check the full address and verify unexpected requests through a trusted route.'},
{id:'webshell',label:'The portal',title:'An unfamiliar file appeared',detail:'At 09:03, the client portal received a file upload. Immediately afterward, a hidden program on the portal was opened. The timing suggests the upload may have introduced it.',lesson:'Two records together tell more than either one alone. The upload and the new hidden program happened seconds apart.'},
{id:'priv',label:'Extra access',title:'A program gained higher access',detail:'At 09:11, a portal program started another program and accessed an administrator permission token. That is unusual for its normal job.',lesson:'A snapshot of what was running can show actions that ordinary file records miss.'},
{id:'egress',label:'The transfer',title:'A large transfer to an unknown address',detail:'At 09:16, the portal sent 42 MB to an unfamiliar internet address. The size and destination are concerning, but this record does not reveal what the data contained.',lesson:'Describe what the record proves. A suspicious transfer does not yet prove which client files, if any, were copied.'}
];
function makeShuffledOrder(n){const a=Array.from({length:n},(_,i)=>i);for(let i=n-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
let state={act:'brief',tab:'mail',found:new Set(),crisis:null,report:null,reportScore:0,hints:0,commandOutput:'',reportAttempts:0,lastClue:null,crisisOrder:makeShuffledOrder(3),reportOrder:makeShuffledOrder(3)};
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function modal(title,body,kicker='CASE NOTES'){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modalKicker').textContent=kicker;$('modal').classList.remove('hidden');$('modalOkay').focus()}
function closeModal(){$('modal').classList.add('hidden')}
$('closeModal').onclick=closeModal;$('modalOkay').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$('helpBtn').onclick=()=>modal('How to play','<p>You are a new investigator checking a possible problem with the client file portal.</p><ol><li>Explore the inbox, portal activity, running programs and data movement. Select clues; simple commands are optional.</li><li>Use the case board to piece together what happened. Three clues unlock the next scene.</li><li>Choose how to protect the files, then explain what you know to the company leader in plain language.</li></ol><p>There is no countdown. Hints are available at every stage, and you can replay the case.</p>');
$('startBtn').onclick=()=>{state.act='investigation';$('brief').classList.add('hidden');$('workspace').classList.remove('hidden');render()};function restartInvestigation(){window.resetInvestigator();state.act='investigation';$('brief').classList.add('hidden');$('workspace').classList.remove('hidden');render();setMaya('Start with the message. What happened next, and do we know if client files were accessed?');window.scrollTo({top:0,behavior:'smooth'})}$('restartInvestigation').onclick=restartInvestigation;
$('guideBtn').onclick=()=>{state.hints++;if(state.act==='investigation'){const next=clues.find(c=>!state.found.has(c.id));const tips={phish:'In Inbox, compare the sender name with the full email address. Look closely at the spelling.',webshell:'In Portal activity, notice what happened immediately after the upload.',priv:'In Running programs, look for a program that gained more access than it normally needs.',egress:'In Data movement, compare the routine transfers with the unusually large one.'};modal('A lead worth following',`<p>${next?tips[next.id]:'You have all four clues. Talk to Maya when you are ready.'}</p>`,'FIELD NOTE')}else if(state.act==='crisis')modal('Think about two goals','<p>Think about two goals: stop the unusual activity and keep useful records. Temporarily disconnecting the affected computers while they stay powered can serve both.</p>','FIELD NOTE');else if(state.act==='report')modal('A clear update','<p>Choose a response that separates what you saw from what remains unknown, then says what happens next.</p>','FIELD NOTE');else modal('Case complete','<p>Try the case again to inspect any missed evidence and compare another containment decision.</p>')};
function collect(id){if(state.found.has(id))return;state.found.add(id);state.lastClue=id;render()}
function renderBoard(){$('boardCount').textContent=`${state.found.size} / 4`;$('board').innerHTML=clues.map((c,i)=>`<div class="node ${state.found.has(c.id)?'filled':''}"><b>${String(i+1).padStart(2,'0')} / ${c.label.toUpperCase()}</b>${state.found.has(c.id)?c.title:'Not found'}</div>`).join('');$('progressPill').textContent=state.act==='investigation'?`${state.found.size} / 4 clues found`:state.act==='crisis'?'Scene 2 of 3':state.act==='report'?'Scene 3 of 3':'Complete'}
function setMaya(text){$('mayaText').textContent=`“${text}”`}
function render(){renderBoard();['investigation','crisis','report','ending'].forEach(id=>$(id).classList.toggle('hidden',state.act!==id));const title={investigation:'Investigate the file portal',crisis:'Protect the files',report:'Scene 3 of 3',ending:'Case review'};const label={investigation:'ACT I / FOLLOW THE CLUES',crisis:'ACT II / THE CRISIS',report:'ACT III / HUMAN RESPONSE',ending:'CASE FILE / DEBRIEF'};$('stageTitle').textContent=title[state.act];$('actLabel').textContent=label[state.act];if(state.act==='investigation')renderInvestigation();if(state.act==='crisis')renderCrisis();if(state.act==='report')renderReport();if(state.act==='ending')renderEnding()}
function renderInvestigation(){document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.tab===state.tab);b.setAttribute('aria-selected',String(b.dataset.tab===state.tab))});$('pane').innerHTML=panes[state.tab]();const last=clues.find(c=>c.id===state.lastClue);$('clueToast').classList.toggle('hidden',!last);$('clueToast').textContent=last?`✦ +5 XP · ${last.title}. ${last.lesson}`:'';$('toCrisis').disabled=state.found.size<3;$('toCrisis').innerHTML=state.found.size<3?`Find ${3-state.found.size} more clue${3-state.found.size===1?'':'s'} <span>›</span>`:'Talk to Maya <span>›</span>';document.querySelectorAll('[data-clue]').forEach(b=>b.onclick=()=>collect(b.dataset.clue));document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>runCommand(b.dataset.command))}
$('toCrisis').onclick=()=>{if(state.found.size<3)return;state.act='crisis';render();setMaya('New alert: another computer is contacting the same unfamiliar address. The client needs access restored soon. What should we do first?')};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;state.commandOutput='';state.lastClue=null;renderInvestigation()});
function collectButton(id,text){return `<button class="inspect ${state.found.has(id)?'found':''}" data-clue="${id}" ${state.found.has(id)?'disabled':''}><span class="plus">${state.found.has(id)?'✓':'+'}</span>${text}</button>`}
const head=(title,subtitle,tag)=>`<div class="source-head"><div><h3>${title}</h3></div><span class="source-tag">${tag}</span></div>`;
const panes={mail:()=>`${head('A message arrived','','08:41')}<div class="mail"><div class="meta"><b>From:</b> Aurora File Support &lt;files@aur0ra-help.example&gt;<br><b>To:</b> team@aurora.example<br><b>Subject:</b> Client access update</div><p>“Open the attachment and sign in to keep access to the client folder.”</p><span class="url">Client_Access_Update.zip</span></div>${collectButton('phish','The sender address looks wrong')}<details class="technical"><summary>Why this matters</summary><p>“aur0ra” uses a zero instead of the letter “o”. An unexpected attachment adds risk.</p></details>`,
logs:()=>`${head('Portal activity','','09:03')}<div class="logbox"><div class="logline"><span class="time">08:58</span> Routine check</div><button class="logline ${state.found.has('webshell')?'found':''}" data-clue="webshell"><span class="time">09:03</span> Upload → hidden program opened <b>+</b></button><div class="logline"><span class="time">09:09</span> Staff dashboard viewed</div></div><details class="technical"><summary>Explore further</summary><p>Optional search: <b>show uploads</b></p><button class="inspect" data-command="show uploads">Run suggested search</button>${state.commandOutput?`<div class="output">${escapeHtml(state.commandOutput)}</div>`:''}<code>POST /upload → /assets/.cache/update.php</code><p>The hidden file may have let someone control the portal.</p></details>`,
memory:()=>`${head('Running programs','','09:11')}<div class="logbox"><div class="logline">Website service → routine task</div><button class="logline ${state.found.has('priv')?'found':''}" data-clue="priv">Website service → administrator access <b>+</b></button><div class="logline">Backup service → scheduled copy</div></div><details class="technical"><summary>Explore further</summary><p>Optional search: <b>show programs</b></p><button class="inspect" data-command="show programs">Run suggested search</button>${state.commandOutput?`<div class="output">${escapeHtml(state.commandOutput)}</div>`:''}<code>PID 448: web-worker → /bin/sh → admin token</code><p>This snapshot shows what was active before the computers were disconnected.</p></details>`,
network:()=>`${head('Data movement','','09:16')}<div class="logbox"><div class="logline">09:12 · Internal service · 18 KB</div><button class="logline ${state.found.has('egress')?'found':''}" data-clue="egress">09:16 · Unknown outside address · 42 MB <b>+</b></button><div class="logline">09:19 · Routine lookup · 2 KB</div></div><details class="technical"><summary>Explore further</summary><p>Optional search: <b>show external</b></p><button class="inspect" data-command="show external">Run suggested search</button>${state.commandOutput?`<div class="output">${escapeHtml(state.commandOutput)}</div>`:''}<code>WEB-03 → 203.0.113.47:8443 · 42 MB OUT</code><p>The record does not show what the data contained.</p></details>`};
function runCommand(raw){const q=raw.trim().toLowerCase();if(!q){state.commandOutput='Try the example shown above, or select a record directly.'}else if(state.tab==='logs'&&/(grep|show|find|cat|search|upload|portal)/.test(q)){state.commandOutput='09:03: File uploaded, then a hidden program opened. The two events happened seconds apart.'}else if(state.tab==='memory'&&/(strings|pslist|process|program|show|find)/.test(q)){state.commandOutput='09:11: The website service started another program and accessed administrator permissions.'}else if(state.tab==='network'&&/(filter|show|find|flow|external|outside|transfer)/.test(q)){state.commandOutput='09:16: 42 MB sent to an unfamiliar outside address. The contents are not yet known.'}else state.commandOutput='No matching result. Try the example above, or select a record directly.';renderInvestigation()}
function renderCrisis(){const chosen=state.crisis;$('crisis').innerHTML=`<div class="phase"><span class="overline">09:22 / NEW ALERT</span><h3>Another computer shows the same activity.</h3><p>The client needs access today. Maya asks: “How do we stop this without losing useful clues?”</p>${chosen===null?`<div class="decisiongrid">${state.crisisOrder.map(i=>{const options=[['contain','Disconnect the affected computers, but keep them on'],['power','Turn both computers off now'],['wait','Keep them connected while we investigate']];return `<button class="decision" data-decision="${options[i][0]}"><strong>${options[i][1]}</strong></button>`}).join('')}</div>`:`<div class="consequence ${chosen==='contain'?'':'risky'}"><h4>${chosen==='contain'?'+30 XP · Activity stopped; clues preserved':chosen==='power'?'+15 XP · Clues lost':'0 XP · Transfer continued'}</h4><p>${chosen==='contain'?'The unusual transfer stops. The team saves a snapshot before restoring access.':chosen==='power'?'The transfer stops, but clues that existed only while the computers were on are lost.':'Another large transfer happens before the team disconnects the computers.'}</p></div><button class="primary" id="toReport">Speak to Alex <span>›</span></button>`}</div>`;document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{state.crisis=b.dataset.decision;render();setMaya(state.crisis==='contain'?'We stopped the activity and kept useful clues. Now tell Alex what we know.':'We stopped the immediate issue. Tell Alex what changed and what remains unknown.')});if($('toReport'))$('toReport').onclick=()=>{state.act='report';render();setMaya('Alex needs the short version: what happened, what is uncertain and what happens next.')}}
const reportLines=[
 {text:'We found an unusual transfer. We do not yet know which files were involved. We have paused access and will update you after checking the records.',score:3,response:'“Thank you. I know what to tell the client, and what is still being checked.”'},
 {text:'The portal is paused and our team is investigating. We will let you know more later.',score:2,response:'“Understood. What did you find, and when should I expect the next update?”'},
 {text:'Client files were stolen. We should tell everyone immediately.',score:0,response:'“Do we know that for certain? Please separate the transfer we saw from what it contained.”'}
];
function renderReport(){const picked=state.report?.choice;$('report').innerHTML=`<div class="phase report report-story"><span class="overline">09:35 / ALEX JOINS THE CALL</span><h3>What do you tell Alex?</h3><div class="report-portrait" aria-hidden="true"></div><div class="report-dialog"><span class="report-speaker">Alex · CTO</span><p>${picked===undefined?'“Were client files taken? What are we doing now?”':`✦ +${reportLines[picked].score*10} XP · ${reportLines[picked].response}`}</p>${picked===undefined?`<div class="vn-replies">${state.reportOrder.map(i=>`<button class="vn-reply" data-report="${i}"><span>You</span>${reportLines[i].text}</button>`).join('')}</div>`:`<button class="vn-next" id="finish">Review the case <span>›</span></button>`}</div></div>`;document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{const choice=Number(b.dataset.report);state.report={choice};state.reportScore=reportLines[choice].score;renderReport();setMaya(state.reportScore===3?'That was clear and careful.':'We need to be precise about what the records prove.')});if($('finish'))$('finish').onclick=()=>{state.act='ending';render();setMaya('Good work. Think about what you found and what remains uncertain.')}}
function renderEnding(){const hard=state.found.size,decision=state.crisis==='contain'?2:state.crisis==='power'?1:0,comm=state.reportScore;const title=decision===2&&comm>=2?'A careful response':'A case with consequences';const missing=clues.filter(c=>!state.found.has(c.id));const reward=window.recordAnalystResult?.(hard,decision,comm);const badge=hard+decision+comm>=8?'Case Solver':hard+decision+comm>=5?'Steady Responder':'First Step';$('ending').innerHTML=`<div class="phase"><span class="overline">CASE 01 / DEBRIEF</span><h3>${title}</h3><p>${decision===2?'The team stopped the unusual activity while keeping useful records.':'Your response changed what the team could learn and whether more data may have left.'} You connected the clues and explained the situation to Alex.</p><p>${state.crisis==='contain'?'The unusual transfer stopped while the team kept a live snapshot.':state.crisis==='power'?'The transfer stopped, but information held only while the computers were on was lost.':'Another transfer happened before the computers were disconnected.'}</p><div class="analyst-reward">✦ ${badge} · ${reward?.xp||0} XP</div><div class="scorecards"><div class="scorecard"><b>${hard}/4</b><span>Clues found</span></div><div class="scorecard"><b>${decision}/2</b><span>Protective action</span></div><div class="scorecard"><b>${comm}/3</b><span>Clear explanation</span></div></div><div class="summary"><h4>What the clues show</h4><ol>${clues.map(c=>`<li><b>${c.label}:</b> ${state.found.has(c.id)?c.title:'Not found in this run'}</li>`).join('')}</ol><h4>What you practised</h4><p>Compare several records before reaching a conclusion. Stop suspicious activity promptly while keeping useful records. Explain what you observed, what you do not know yet and what happens next.</p>${missing.length?`<p><b>Try another run:</b> revisit ${missing.map(c=>c.label.toLowerCase()).join(' and ')}.</p>`:''}</div><div class="ending-actions"><button class="ghost" id="restart">Try again</button><button class="primary" id="backCatalog">Back to sections <span>›</span></button></div></div>`;$('restart').onclick=restartInvestigation;$('backCatalog').onclick=()=>window.showCourseCatalog?.()}
